# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HybridDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HybridDemo
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'SwiftyJSON'
  pod 'Zip'
  pod 'R.swift'
  pod 'GCDWebServer'

end
