platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'HybridDemo' do

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'SwiftyJSON'
  pod 'R.swift'
  pod 'MBProgressHUD', '~> 1.0.0'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
